#!/usr/bin/env python3
"""
Setup Script for Enhanced OTT Bot
Helps configure the bot for first-time use
"""
import sys
import os
from pathlib import Path

def print_header():
    print("""
╔═══════════════════════════════════════════════════════════╗
║       🤖 Enhanced OTT Bot - Setup Wizard 🤖              ║
╚═══════════════════════════════════════════════════════════╝
    """)

def print_step(step, description):
    print(f"\n{'='*60}")
    print(f"STEP {step}: {description}")
    print('='*60)

def check_env_file():
    """Check if .env file exists"""
    env_path = Path(__file__).parent / '.env'
    return env_path.exists()

def get_user_input(prompt, default=None, required=True):
    """Get user input with optional default"""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    while True:
        value = input(prompt).strip()
        if not value and default:
            return default
        elif not value and not required:
            return ""
        elif value:
            return value
        else:
            print("⚠️  This field is required. Please enter a value.")

def main():
    print_header()
    
    print("""
Welcome to the Enhanced OTT Bot Setup!

This wizard will help you configure your bot in a few simple steps.

Prerequisites:
✓ Telegram Bot Token (from @BotFather)
✓ MongoDB Database
✓ Channel IDs for force subscribe (optional)
✓ UPI ID for payments

Let's get started! 🚀
    """)
    
    input("Press Enter to continue...")
    
    # Step 1: Bot Credentials
    print_step(1, "Bot Credentials")
    print("\nCreate a bot via @BotFather on Telegram to get your bot token.")
    
    bot_token = get_user_input("Enter your Bot Token", required=True)
    api_id = get_user_input("Enter API_ID", default="24271861", required=False)
    api_hash = get_user_input("Enter API_HASH", default="fc5e782b934ed58b28780f41f01ed024", required=False)
    
    # Step 2: Database
    print_step(2, "Database Configuration")
    print("\nEnter your MongoDB connection details.")
    
    db_uri = get_user_input(
        "MongoDB URI",
        default="mongodb+srv://shankar113:pkfZ2NlPLngYvo73@cluster0.52v0v.mongodb.net/?retryWrites=true&w=majority",
        required=False
    )
    db_name = get_user_input("Database Name", default="techvjautobot", required=False)
    
    # Step 3: Channels & Admin
    print_step(3, "Channels & Admin Setup")
    print("\nNote: Use channel ID (e.g., -1001234567890) not username.")
    
    admin_id = get_user_input("Your Telegram User ID (Admin)", required=True)
    log_channel = get_user_input("Log Channel ID", default="-1002409317177", required=False)
    auth_channel = get_user_input("Force Subscribe Channel ID (leave empty to disable)", required=False)
    
    # Step 4: Payment Details
    print_step(4, "Payment Configuration")
    
    owner_username = get_user_input("Owner Telegram Username (without @)", default="Shankar_Kola", required=False)
    payment_qr = get_user_input("Payment QR Code Image URL", default="https://envs.sh/L-M.jpg", required=False)
    
    # Step 5: Links & Groups
    print_step(5, "Community Links")
    
    grp_link = get_user_input("Group Link", default="https://t.me/chillbot_movie", required=False)
    channel_link = get_user_input("Channel Link", default="https://t.me/+nsKuewNAKQtkMGJl", required=False)
    tutorial = get_user_input("Tutorial Link", default="https://t.me/how_to_open_link_time2chill", required=False)
    support_chat = get_user_input("Support Chat Username", default="time2chill_discussion", required=False)
    
    # Step 6: Features
    print_step(6, "Feature Configuration")
    
    premium_mode = get_user_input("Enable Premium & Referral System? (yes/no)", default="yes", required=False)
    auto_approve = get_user_input("Enable Auto Approve for channels? (yes/no)", default="yes", required=False)
    imdb_enabled = get_user_input("Enable IMDB Integration? (yes/no)", default="yes", required=False)
    
    # Generate .env content
    print_step(7, "Generating Configuration")
    
    env_content = f"""# Enhanced OTT Bot Configuration
# Generated by setup_bot.py

# Bot Credentials
API_ID="{api_id}"
API_HASH="{api_hash}"
BOT_TOKEN="{bot_token}"
TELEGRAM_BOT_TOKEN="{bot_token}"

# Database
DATABASE_URI="{db_uri}"
DATABASE_NAME="{db_name}"
DB_NAME="{db_name}"
MONGO_URL="mongodb://localhost:27017"

# Admins & Channels
ADMINS="{admin_id}"
LOG_CHANNEL="{log_channel}"
AUTH_CHANNEL="{auth_channel if auth_channel else ''}"
CHANNELS="-1002309517928"
AUTH_USERS="{admin_id}"

# Force Subscribe
REQUEST_TO_JOIN_MODE="False"
TRY_AGAIN_BTN="False"
REQST_CHANNEL_ID=""
SUPPORT_CHAT_ID=""

# Premium & Referral
PREMIUM_AND_REFERAL_MODE="{'True' if premium_mode.lower() in ['yes', 'y', 'true'] else 'False'}"
REFERAL_COUNT="20"
REFERAL_PREMEIUM_TIME="1month"
PAYMENT_QR="{payment_qr}"
OWNER_USERNAME="{owner_username}"

# Links
GRP_LNK="{grp_link}"
CHNL_LNK="{channel_link}"
TUTORIAL="{tutorial}"
SUPPORT_CHAT="{support_chat}"

# Bot Settings
SESSION="TechVJBot"
CACHE_TIME="1800"
PICS="https://envs.sh/L-f.jpg"
NOR_IMG="https://graph.org/file/b69af2db776e4e85d21ec.jpg"
MELCOW_VID="https://t.me/How_To_Open_Linkl"
SPELL_IMG="https://te.legra.ph/file/15c1ad448dfe472a5cbb8.jpg"

# Features
IMDB="{'True' if imdb_enabled.lower() in ['yes', 'y', 'true'] else 'False'}"
AUTO_APPROVE_MODE="{'True' if auto_approve.lower() in ['yes', 'y', 'true'] else 'False'}"
PM_SEARCH="True"
IS_TUTORIAL="True"
P_TTI_SHOW_OFF="False"
AUTO_DELETE="True"
SINGLE_BUTTON="True"
LONG_IMDB_DESCRIPTION="False"
SPELL_CHECK_REPLY="True"
MELCOW_NEW_USERS="True"
PROTECT_CONTENT="False"
NO_RESULTS_MSG="False"

# Shortlink (Mock)
SHORTLINK_MODE="False"
SHORTLINK_URL="https://runurl.in/"
SHORTLINK_API="02d038634b0ed6e5245e2502243d494f87df3c57"

# Other Settings
MAX_B_TN="5"
PORT="8080"
MSG_ALRT="Hello My Dear Friends ❤️"
MULTIPLE_DATABASE="False"
COLLECTION_NAME="vjcollection"
CORS_ORIGINS="*"
WIDEVINE_API_KEY="wv_mock_key_12345"
ADMIN_UPI_ID="admin@upi"

# User Limits
FREE_USER_DAILY_LIMIT=10
PREMIUM_USER_DAILY_LIMIT=100
ADMIN_USER_DAILY_LIMIT=999999

# Video Configuration
MAX_DOWNLOAD_SIZE_MB=500
ALLOWED_QUALITIES="360p,480p,720p,1080p,1440p,4k"
DOWNLOAD_TIMEOUT_SECONDS=300

# Rate Limiting
RATE_LIMIT_WINDOW_SECONDS=86400
RATE_LIMIT_ENABLED=true
"""
    
    # Write to .env file
    env_path = Path(__file__).parent / '.env'
    
    if env_path.exists():
        backup = input("\n⚠️  .env file already exists. Create backup? (yes/no): ")
        if backup.lower() in ['yes', 'y']:
            backup_path = env_path.with_suffix('.env.backup')
            env_path.rename(backup_path)
            print(f"✓ Backup created: {backup_path}")
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"\n✓ Configuration saved to: {env_path}")
    
    # Final instructions
    print_step(8, "Setup Complete! 🎉")
    
    print("""
Your Enhanced OTT Bot is now configured!

Next Steps:
1. Review the configuration in .env file
2. Restart the backend service:
   sudo supervisorctl restart backend

3. Start using your bot:
   - Search for your bot on Telegram
   - Send /start command
   - Configure channels and test features

4. For detailed documentation, see:
   /app/ENHANCED_BOT_GUIDE.md

Important Notes:
✓ Make your bot admin in AUTH_CHANNEL for force subscribe
✓ Add LOG_CHANNEL ID to receive notifications
✓ Update PAYMENT_QR with your actual QR code
✓ Test payment flow before going live

Need Help?
- Check logs: tail -f /var/log/supervisor/backend.err.log
- Review guide: cat /app/ENHANCED_BOT_GUIDE.md
- Contact: @{owner_username}

Happy bot-ing! 🚀
    """)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)
